language: python
python:
- 3.7
install:
- python setup.py sdist
- pip install dist/*
script:
- mkdir testing
- cp test_exppy.py testing
- cd testing
- python test_expy.py
- cd ..
deploy:
  provider: pypi
  user: mwojc
  password:
    secure: l5toy5lYfs2KDa0jQbDVj1vE795hFexm4XkE/ndv4sfOzNLqAnCK+GzSm8gA80cOfBS8YjjHfxfaS05ccCHLSf3Jxj7sxfLEAUdksFYYPQxtX2WiUNsVHN+GKVD1xDZgR+mYhSb88BK76wVMjdhbucBLDiRHlAKCz1TEPn0iP1lGUEAcNkSd2fK3rgwmpsG5c5mMbVEgix+EjntxZ/lKv4d33pSkWiuGDkGDZv7FZgV5mXYXaYM1tCLa3e6j0RZdVPETs243DodznW0rokhgOVzIoMQxKIrU7NuwP1QgvX1cJYqcy3iJc8rZktV0wm8Z2qNmB7kA4nvHKdp7GGNy3wSlunitVSb6e4jMZr6JxkQhJZQuiJCrbxoARQEg1z1Mpxn52oeAd9b8ZkaPrXT5GmGqvgtPmgKJ2FVzK1fXpf+Z9M605yrSLRgoETqpORHHOZ+68MCC328ohUC7EWUYg1l2CAgU7EN8YlIU2ZvOKiAOrFgCZodrgvzXuUppXBy7Jrh0SsxwTLXcqf/YYsCMN/5mDnpqOxLKx3BR7/nJ6H7akqP1hU60X0qpFLfF2kCcU1HnkcQzphSmkaeD50OErtwJPsD+Xdoq5tC0JozzihKkm8RZ5Ywy0LnzKxSeHv5dKUJtXQA2V8iH25TWENQ69G2Mg7sN2HBEPXh12OlxJjA=
  distributions: sdist
  skip_cleanup: true
  on:
    tags: true
    branch: master
